apiVersion: v2
name: exchange-rates
description: A Helm chart for the HeyCar technical challenge

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
