name: Build docker image
on:
  push:
    paths:
      - exchange-rates/**
      - .github/**
      - .custon-ci-actions/**
    branches:
      - main
      - staging
      - stable
  pull_request:
    paths:
      - exchange-rates/**
      - .github/**
      - .custon-ci-actions/**
    branches:
      - main
      - staging
      - stable

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with registry
        run: |
          echo "${{secrets.REGISTRY_PASSWORD}}" | docker login -u "${{secrets.REGISTRY_USER}}" ${{secrets.REGISTRY_URI}} --password-stdin
      - name: Checkout code
        uses: actions/checkout@v2
      - name: generate semantic version
        id: semver
        uses: ./.custon-ci-actions/semver-tag-generator/
        with:
          sub-path: 'exchange-rates'
      - name: Package and publish
        run: ./.github/.scripts/docker-build.sh
        env:
          DOCKER_BUILDKIT: 1
          REGISTRY_URI: ${{secrets.REGISTRY_URI}}
          DOCKER_PROJECT: piximos
          IMAGE_NAME: crypto-exchange
          DOCKER_IMAGE_PATH: 'exchange-rates/Dockerfile'
          DOCKER_BUILD_CONTEXT: 'exchange-rates/.'
          GITHUB_EVENT: ${{ github.event_name }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          GITHUB_PR_BASE_BRANCH: ${{ github.base_ref }}
          GITHUB_BRANCH: ${{ github.ref }}
          SEMVER_TAG: ${{ steps.semver.outputs.semver }}
          BUILD_HEAP_SIZE: ${{secrets.BUILD_HEAP_SIZE}}
