name: pr-checks
on:
  pull_request:

jobs:
  scan-vulnerabilities:
    name: Scan vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Scan app vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'vulnerabilities-report.json'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: '0'
          scan-ref: './exchange-rates/'
      - name: generate semantic version
        id: semver
        uses: ./.custon-ci-actions/trivy-scan-report-parser/
        with:
          sub-path: 'exchange-rates'
          input-file: 'vulnerabilities-report.json'
          output-file: './pr-feedback.md'
          package-json-path: 'exchange-rates/package.json'
      - name: Comment vulnerabilities on PR
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: These following vulnerabilities were found
          recreate: true
          path: './pr-feedback.md'

